--- #YAML:1.0
name:                Captcha-reCAPTCHA-Mailhide
version:             0.93
abstract:            A Perl implementation of the reCAPTCHA Mailhide API
license:             perl
author:              
    - Andy Armstrong <andy@hexten.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Crypt::Rijndael:               0
    HTML::Tiny:                    0.904
    MIME::Base64:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
